---
- name: Setting Frontend Application
  hosts: local
  become: no

  vars:
    deployment_name: "frontend-deployment"
    app_namespace: "portfolio-frontend-namespace"
    app_name: "portfolio-frontend"
    image_name: "sohith18/portfolio-frontend:latest"
    container_port: 80
    memory_request: "64Mi"
    memory_limit: "256Mi"

    ingress_name: "frontend-ingress"
    ingress_host: "portfolio-builder.com"
    path: "/"

  tasks:
    - name: Include Common Role
      include_role:
        name: common

    - name: Include Ingress Role
      include_role:
        name: ingress