---
- name: Setting Backend Server
  hosts: local
  become: no

  vars:
    deployment_name: "model-deployment"
    app_namespace: "portfolio-model-namespace"
    app_name: "portfolio-model"
    image_name: "sohith18/portfolio-builder-model:latest"
    container_port: 8000

    ingress_name: "model-ingress"
    ingress_host: "model.portfolio-builder.com"
    path: "/api"

  tasks:
    - name: Include Common Role
      include_role:
        name: common